[package]
name = "rustscript-difftest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rustscript-core = { workspace = true, features = ["generator-support"] }
rand_chacha.workspace = true
rand_core.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
wait-timeout.workspace = true
